### PR TITLE
Correct eval

### PR DESCRIPTION
**Pull request by proofit404**
See https://github.com/xquery-mode/cider-any/issues/14

### CODE REVIEW

**Comment by m-g-r** [comment]
Thanks, Artem!

Keep in mind my recent bugfix in commit
https://github.com/xquery-mode/xdbc-selector/commit/67a93889530eeb6283265e644bdbfbda2af6d704
Does your code still check that a cider connection exists?

Also, I took over the convention from cider that the form to be evaluated is also printed to a buffer  cider-read-eval-buffer. At first I was confused about it. It seems that it is for error checking so that you can look at what was sent. Or do you see any other reason behind that? I'm not sure whether that is necessary, or useful.

Best regards,
Max

**Comment by m-g-r** [comment]
I can confirm that this doesn't check for the cider-connection but just files with a non-helpful error, caused by trying to use a connection that doesn't exist.

**Comment by proofit404** [comment]
On `cider-read-eval-buffer`

It is implementation detail of `cider-read-and-eval` function.  It reads clojure expression, inserts it into this buffer, then it calls `cider-interactive-eval` function **within** this buffer.  `cider-interactive-eval` on its side calls `cider--prep-interactive-eval` for some utility stuff before actual evaluation.  One of this utility steps is `cider-eval-ns-form`.  It will search ns form in current buffer (it is `cider-read-eval-buffer` in this case) and evaluate this ns form in the user namespace.  After that `cider-interactive-eval` can use this ns to evaluate original for we typed into minibuffer.

All this machinery is necessary for evaluation in the namespace of current buffer.

But we specify ns explicitly and don't need those extra steps to find current namespace.  Most of times `cider-eval-form` will be called within xquery buffers any way.  You can see it in following example.

``` elisp
(cider-eval-form "(str *ns*)")
=> "user"
(cider-eval-form "(str *ns*)" "clojure.string")
=> "clojure.string"
```

I don't think we need to support `cider-read-eval-buffer` in any case.

**Comment by m-g-r** [comment]
xdmp-list-documents got a bit longer, and it might be interesint to see what xquery is acutally sent. But I agree that your short versions actually do what is necessary.

**Comment by proofit404** [comment]
Oops. I don't know that some visual glitches were introduced by my changes. Should I correct them?

**Pull request merged**
